12-07-Friday 20:28:51 - spider.py[line:122] - WARNING: Traceback (most recent call last):
  File "spider.py", line 118, in <module>
    spider.publish()
  File "spider.py", line 111, in publish
    self.__mail(e_info['title'],e_content)
  File "spider.py", line 99, in __mail
    smtpObj.connect(HOST, 25)    # 25 为 SMTP 端口号
  File "/usr/lib64/python3.6/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib64/python3.6/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/lib64/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib64/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

